dist: xenial
services:
  - postgresql
addons:
  postgresql: '10'
language: elixir
elixir: '1.7'
otp_release: '21.0'
before_script:
  - cd services/fc_identity; mix deps.get; mix event_store.create; mix event_store.init
  - cd ../../; mix freshcom.setup
script:
  - cd services/fc_identity; mix test
  - cd ../../; mix test
env:
  global:
    - EVENTSTORE_DB_USERNAME="postgres"
    - EVENTSTORE_DB_PASSWORD=""
    - PROJECTION_DB_USERNAME="postgres"
    - PROJECTION_DB_PASSWORD=""
    - MIX_ENV="test"