services:
  - postgresql
addons:
  postgresql: "10.4"
language: elixir
elixir: '1.7'
before_script:
  - mix freshcom.setup
script:
  - mix test
env:
  - DB_USERNAME="postgres"
  - DB_PASSWORD="postgres"